name: Release

on:
  push:
    branches: [release]

jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: See dist
        shell: bash
        run: |
          cd dist
          ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.deb
            dist/*.yml
            dist/*.blockmap

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload_to_google_drive
          overwrite: true
          path: |
            dist/*.exe
            dist/*.deb
            dist/*.yml
            dist/*.blockmap
